const OVERVIEW_CARD_MAP = {
    alertCount: "告警数量",
    avgBandwidth: "平均带宽",
    avgClientLatency: "平均服务端延迟",
    avgUpstreamBandwidth: "平均上行带宽",
    clientRetransmissionRate: "重传率",
    dataPacketRetransmissionRate: "数据包重传率",
    peakBandwidth: "峰值带宽",
    serverRetransmissionRate: "服务端重传率",
    totalPackets: "总数据包",
    totalTraffic: "总流量"
} 

const expandDataMap = {
    arch: "体系架构",
    archType: "类型",
    completeRevision: "完整版本",
    controllerIp: "控制IP",
    cpuNum: "CPU数",
    createTime: "创建时间",
    ctrlIp: "控制IP",
    ctrlMac: "控制Mac地址",
    curAnalyzerIp: "当前分析IP",
    curControllerIp: "当前控制IP",
    currentK8sImage: "当前K8s镜像",
    kernelVersion: "内核版本",
    launchServer: "软件版本",
    licenseType: "许可类型",
    memorySize: "内存大小",
    name: "采集器名称",
    os: "操作系统",
    regionName: "区域",
    revision: "版本",
    state: "状态",
    updateTime: "更新时间",
    vtapGroupName: "采集器组",
    analyzerIp: "分析IP"
}

const basicDataMap = {
    // 基础配置
    agentLcuuid: "代理唯一标识符（UUID）",
    agentName: "代理名称",
    analyzerIp: "分析器IP地址",
    analyzerPort: "分析器端口号",
    appFlowLogSpanid: "应用日志SpanID字段名",
    appFlowLogTraceid: "应用日志链路追踪ID字段名",
    appLogCollectRate: "应用日志采集速率（条/秒）",
    appLogEnableNetPos: "应用日志网络位置采集范围",
    appLogParseLength: "应用日志解析长度（字节）",
    appPerfMetricData: "是否采集应用性能指标",
    bareUdpVlan: "裸UDP VLAN标签",
    callLogIgnorePoint: "调用日志忽略点",
    clockSync: "是否启用时钟同步",
    cloudResourceDown: "云资源降级策略",
    collectNicRegex: "采集网卡的正则匹配",
    configPullInterval: "配置拉取间隔（秒）",
    containerClusterInnerIpDown: "容器集群内IP降级范围",
    controllerIp: "控制器IP地址",
    controllerPort: "控制器端口号",
    cpuCoreLimit: "CPU核心数限制",
    cpuMillicoreLimit: "CPU毫核限制（千分之一核）",
    dataIntegrationPort: "数据集成服务端口",
    dataIntegrationService: "是否启用数据集成服务",
    dataSocket: "数据传输协议",
    dispatchFuseMonitorInterval: "熔断监控间隔（秒）",
    dispatchFuseThresholdMbps: "流量分发熔断阈值（Mbps）",
    dispatchLimitMbps: "流量分发带宽限制（Mbps）",
    dispatchSocket: "分发传输协议",
    flowLogCollectRate: "流量日志采集速率（条/秒）",
    flowLogEnableNetPos: "流量日志网络位置采集范围",
    flowLogIgnorePoint: "流量日志忽略点",
    globalDedup: "是否启用全局去重",
    httpLogProxyClient: "HTTP日志代理客户端IP字段",
    httpLogXrequestid: "HTTP日志请求ID字段",
    inactiveIpMetricData: "是否采集非活跃IP指标",
    inactivePortMetricData: "是否采集非活跃端口指标",
    innerAdditionalHeader: "内部附加头字段",
    logFileSizeMb: "单个日志文件大小限制（MB）",
    logLevel: "日志级别",
    logSend: "是否发送日志到远程",
    logSendRatePerHour: "日志发送速率（条/小时）",
    logStoreDays: "日志存储天数",
    maxEscapeTime: "最大逃逸时间（毫秒）",
    memoryLimitMb: "内存限制（MB）",
    metricData: "是否采集基础指标数据",
    netPerfMetricData: "是否采集网络性能指标",
    packetLength: "截取的数据包长度（字节）",
    packetLimitKpps: "数据包捕获速率限制（千包/秒）",
    pcapSocket: "抓包传输协议",
    processLimit: "进程数限制",
    requestNatIp: "是否请求NAT转换IP",
    resourceReportInterval: "资源上报间隔（秒）",
    secondMetricData: "是否采集秒级指标数据",
    soPlugins: "动态链接库插件列表",
    syncResourceInfo: "是否同步资源信息",
    systemIdleMemPercent: "系统空闲内存百分比阈值",
    systemLoadFuseMetric: "系统负载监控指标",
    systemLoadFuseRecover: "系统负载恢复阈值",
    systemLoadFuseThreshold: "系统负载熔断阈值",
    threadLimit: "线程数限制",
    trafficApi: "流量API模式",
    trafficFilter: "流量过滤规则",
    trafficMode: "流量采集模式",
    tunnelDecapType: "隧道解封装类型",
    udpMaxMtu: "UDP最大MTU值",
    vmMacParse: "虚拟机MAC解析方式",
    vmXmlFolder: "虚拟机XML配置文件路径",
    wasmPlugins: "WASM插件列表"
}

export {
    OVERVIEW_CARD_MAP,
    expandDataMap,
    basicDataMap
}